all: subdirs

subdirs:
	$(MAKE) -C Mediator
	$(MAKE) -C Decorator
	$(MAKE) -C Bridge
	$(MAKE) -C Facade
	$(MAKE) -C Adapter
	$(MAKE) -C ChainOfResponsibility
	$(MAKE) -C Factory
	$(MAKE) -C AbstractFactory

clean:
	$(MAKE) -C Mediator clean
	$(MAKE) -C Decorator clean
	$(MAKE) -C Bridge clean
	$(MAKE) -C Facade clean
	$(MAKE) -C Adapter clean
	$(MAKE) -C ChainOfResponsibility clean
	$(MAKE) -C Factory clean
	$(MAKE) -C AbstractFactory clean
