all: subdirs

subdirs:
	make -C Mediator
	make -C Decorator
	make -C Bridge
	make -C Facade
	make -C Adapter
	make -C ChainOfResponsibility

clean:
	make -C Mediator clean
	make -C Decorator clean
	make -C Bridge clean
	make -C Facade clean
	make -C Adapter clean
	make -C ChainOfResponsibility clean
